Add D4T into codeart
m-zakeri/CodART pull request #144
Opened 2024-07-06 13:18 UTC by Narges-abbasii

2024-07-14 08:37 UTC, m-zakeri commented
Add only refactoring and testability measurement modules
not all files, not common files.

2024-07-23 06:53 UTC, Narges-abbasii commented
I reviewed the files and made the necessary changes. Also, I put the Gorgeous/Resources directory into gitignore if it is not enough let me know thank you.

2024-07-23 07:52 UTC, m-zakeri requested changes
Many irrelevant files and changes. 
Please consider fixing the request.

2024-07-24 11:28 UTC, Narges-abbasii commented
I resolved irrelevant files problem

2024-07-24 12:09 UTC, m-zakeri requested changes
Requirements contain repeated items. 
Generate the requirements file automatically to resolve problems

2024-07-24 12:09 UTC, m-zakeri commented on requirements.txt
Requirements contain repeated items. 
Please check and fix.

2024-07-25 07:22 UTC, Narges-abbasii commented
removed duplicate versions of libraries in requirement.txt

2024-07-25 15:46 UTC, m-zakeri approved these changes

2024-07-25 15:46 UTC, merged